### ISSUE TITLE
Feature request: support retrieving sealed subclasses

### ISSUE THREAD

**Issue by ZacSweers** [JetBrains-Research/reflekt#71]
Since these are known at compile-time, it would be quite helpful to be able to generate that information.

**Comment by CommanderTvis** [comment]
Isn't it covered by `KClass.sealedSubclasses`?

**Comment by ZacSweers** [comment]
@nbirillo I've implemented a working prototype of this as an IR transform here. Would you be interested in a PR of that to this project? If not I'll just release it as its own project

https://github.com/ZacSweers/MoshiX/pull/272

**Comment by nbirillo** [comment]
Hello! It looks great! 

However, we changed a lot of main logic in Reflekt since we are deleting the old front-end from the plugin
The current changes are available [here](https://github.com/JetBrains-Research/reflekt/pull/114) (in the `delete-old-front-end` branch). @elena-lyulina are finishing with replacing all tests into tests with the tests compiler framework (it is available in the official kotlin repo), after that we will merge all changes to the master branch (approximately in several days)
After that, the core architecture will be stable since we will use only stable parts for the Kotlin compiler (in our case only IR backend) and we will complement new features and so on
If you have time to merge your changes with the `delete-old-front-end` branch (I can help you if you want) the changes will be beneficial for our project
In your case what way to interact with Reflekt do you prefer? a new type of query in DSL? 

Also, we will implement some wrappers to get not only entities but the information about them (see [this](https://github.com/JetBrains-Research/reflekt/issues/112) issue) to avoid run-time reflection after getting the entities. We are going to have information about sealed subclasses

**Comment by ZacSweers** [comment]
Happy to. Do you want me to PR something against that branch or just wait until it's merged?

> In your case what way to interact with Reflekt do you prefer? a new type of query in DSL?

The way I've implemented actually just replaces the `KClass.sealedSubclasses` calls (which otherwise would be an error to call at runtime) during IR transformation so it doesn't require any sort of new runtime API/DSL.

If #112 is implemented though, I would expect that to supersede the need for my implementation since it offers an alternative mechanism. Let me know either way.

**Comment by CommanderTvis** [comment]
> Happy to. Do you want me to PR something against that branch or just wait until it's merged?
> 
> > In your case what way to interact with Reflekt do you prefer? a new type of query in DSL?
> 
> The way I've implemented actually just replaces the `KClass.sealedSubclasses` calls (which otherwise would be an error to call at runtime) during IR transformation so it doesn't require any sort of new runtime API/DSL.
> 
> If #112 is implemented though, I would expect that to supersede the need for my implementation since it offers an alternative mechanism. Let me know either way.

The problem with replacing `KClass` calls is that it may break cases when the user really wants runtime reflection (however, it seems to be OK since it's obviously impossible to add new sealed subclass at run-time). Another one is that such calls produce an allocation for `listOf`, so static registry would be more efficient.

**Comment by nbirillo** [comment]
In fact, replacing calls to `KClass` directly can confuse users, since in this case some of the calls will be in runtime, and some will be in compile-time

You can try to add it marked experimental. Also, I see you use descriptors in the implementation, they will be removed in future versions of the compiler, so they should be removed anyway

[#112](https://github.com/JetBrains-Research/reflekt/issues/112) and incremental compilation are first what should we do after merging the current changes.

@elena-lyulina What do you think? Do we want to try adding these changes as experimental ones?

**Comment by CommanderTvis** [comment]
We can't mark `KClass.sealedSubclasses` experimental since it is in Kotlin's module.

**Comment by nbirillo** [comment]
I know, I mean mark it internally

**Comment by ZacSweers** [comment]
A separate entry-point could be used as well, I just used that as a convenience since it was similar to how `kotlin-reflect`'s presence works.

> Also, I see you use descriptors in the implementation, they will be removed in future versions of the compiler, so they should be removed anyway

Unfortunately it doesn't seem like this is implemented outside of descriptors yet, but perhaps that's changed in kotlin 1.6 or 1.7. I'll take a look

> Another one is that such calls produce an allocation for listOf, so static registry would be more efficient.

Fair. I considered this a bit low overhead but we could also generate it as a singleton list somewhere and just return that

**Comment by ZacSweers** [comment]
Looks like they're present now (or I missed them before!), updated the impl with descriptors removed now 👍

**Comment by ZacSweers** [comment]
that could work, or an alternative to using FIR could just be to create a placeholder function that's replaced (if you look in the earlier commits of the PR, this is how I started it). If you don't want to ship a runtime artifact, this could be exposed as a gradle plugin DSL with an fqname to a consumer-provided function (similar to how all-open and related plugins allow users to bring their own annotations). What do you think?

**Comment by nbirillo** [comment]
I think this is better than replacing the runtime artefact 👍

**Comment by nbirillo** [comment]
It will be fixed by [issue#112](https://github.com/JetBrains-Research/reflekt/issues/112)
