### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by nordiauwu** [JetBrains-Research/reflekt#84]

**Comment by nbirillo** [comment]
@nordiauwu Hello! 
Yes, we are currently working on this project. We redesigned a part of the work with libraries since our old approach was broken, and we rewrote the analysis part to the compiler descriptors.

Our nearest current plans:
- support incremental compilation (to do it we have to do some tricks inside the API of the Kotlin compiler, so it takes a much longer time than we expected)
- support sealed subclasses
- return annotations lists together with functions and classes if a flag is done

I hope we will release a new version before the NY holidays

**Comment by nordiauwu** [comment]
I'm glad you haven't given up on this, I'm looking forward to the next release 👍
